###Lista de users
GET http://localhost:3000/users

###Get user
GET http://localhost:3000/users/9af02ad0-052b-4fa7-b9d8-0fd36deea3e2

###Criar user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste90@example.com",
  "password": "123456"
}  

###Atualizar user
PATCH http://localhost:3000/users/0ba019f2-6f87-4c04-b116-6374b67353ba
Content-Type: application/json

{
  "email": "teste10@hotmail.com"
}

###Deletar user
DELETE http://localhost:3000/users/9af02ad0-052b-4fa7-b9d8-0fd36deea3e2