###Lista de users
GET http://localhost:3000/users

###Get user
GET http://localhost:3000/users/9570676f-7d58-4234-94e7-1ca4db8171d0

###Criar user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Teste15",
  "email": "teste15@example.com",
  "password": "123456"
}  

###Atualizar user
PATCH http://localhost:3000/users/9570676f-7d58-4234-94e7-1ca4db8171d0
Content-Type: application/json

{
  "email": "teste1@example.com"
}

###Deletar user
DELETE http://localhost:3000/users/5633a1ba-e18d-4f09-a413-6e9428123fec